### ISSUE TITLE
Filen 支持

### ISSUE THREAD

**Issue by yucho123987** [AlistGo/alist#6726]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加对 Filen 的支持。

### Suggested solution / 实现思路

添加 Filen 驱动

### Additional context / 附件

Filen 官网：https://filen.io/

_No response_

**Comment by GD2021** [comment]
+1

**Comment by 0123-smallbottle** [comment]
+1

**Comment by Wsine** [comment]
I just found the official [Filen SDK](https://github.com/FilenCloudDienste/filen-sdk-ts), [WebDAV server](https://github.com/FilenCloudDienste/filen-webdav), and [Docker wrapper](https://github.com/xiao-cold/efilen-webdav) for the reference. I am glad to see if some capable one can integrate it with alist.

**Comment by jochne** [comment]
+1, plz

**Comment by YujiaCheng1996** [comment]
https://github.com/FilenCloudDienste/filen-sdk-go 这个官方的sdk稳定以前很难吧

**Comment by yucho123987** [comment]
> https://github.com/FilenCloudDienste/filen-sdk-go 这个官方的sdk稳定以前很难吧

我目前使用的方案是借助 Filen 官方的 Node.js SDK 运行一个 WebDAV 服务器，然后在 Alist 中添加，已经稳定使用几个月了。没试过 Go SDK
