### ISSUE TITLE
添加腾飞webos网盘

### ISSUE THREAD

**Issue by david88558855** [AlistGo/alist#6999]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

添加腾飞webos网盘

**Comment by yaoice** [comment]
腾飞webos网盘官网上，似乎没找到对应的API接口文档

**Comment by david88558855** [comment]
> 腾飞webos网盘官网上，似乎没找到对应的API接口文档

https://github.com/fs185085781/webos     在这个开源页面看看有没线索

**Comment by yaoice** [comment]
> > 腾飞webos网盘官网上，似乎没找到对应的API接口文档
> 
> https://github.com/fs185085781/webos 在这个开源页面看看有没线索
这个链接跳转过去的API文档，写的不清楚，集成起来难度比较大，还得去看它的源码，验证它的接口是否ok
<img width="1582" alt="image" src="https://github.com/user-attachments/assets/1e296637-af7a-483e-b121-48bfe19be766">
<img width="1553" alt="image" src="https://github.com/user-attachments/assets/eddcb1f7-c6f2-447a-86de-5d352a54c7e2">
