### ISSUE TITLE
任何格式的视频视频都无法播放，音频文件可以。不知道是什么原因

### ISSUE THREAD

**Issue by caixin1218** [AlistGo/alist#7070]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

任何格式的视频视频都无法播放，音频文件可以。不知道是什么原因,2个月前是可以播放的。

**Comment by Simonzhang8** [comment]
提供一下具体的信息，存储驱动用的哪个，下载模式是什么，以及复现的链接

**Comment by caixin1218** [comment]
我使用的是lede 源码编译的openwrt系统 
添加 https://github.com/sbwml/luci-app-alist 插件 选择3.35.0这个版本编译的，7天前有过一次更新后就发现视频无法播放了
操作如下 ：
git clone https://github.com/sbwml/luci-app-alist
git tag 
git checkout 3.35.0

存储驱动是内置的sata 驱动，通过samba4挂载 。文件也是没有问题的，fiilebrowser 是可以正常播放的。

**Comment by caixin1218** [comment]
![IMG_2113](https://github.com/user-attachments/assets/c259a9a3-f33f-409f-845e-63d815df819a)
