### ISSUE TITLE
希望添加“T-drive”支持，就是“telegram”里的收藏夹

### ISSUE THREAD

**Issue by wengzhenquan** [AlistGo/alist#7081]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

telegram里的网盘是无限空间、无限流量、不限速的免费网盘，非常棒。
T-drive的下载渠道只有一种，是windows上的微软商店，它的原理是调用telegram官方提供的API。

### Suggested solution / 实现思路

1、我看到alist能够支持谷歌网盘，说明对外面的网盘是可以支持的。

2、并且据我所知，“T-drive”也不是电报官方的，是第三方开发者做的，实际上就是用了telegram里的“收藏夹”，也就是说，这是完全可以实现第三方的。
希望alist能够添加支持。

**Comment by im-dashan** [comment]
支持，我也想要
