### ISSUE TITLE
阿里云盘Open 新建的存储获取文件列表报错

### ISSUE THREAD

**Issue by zhoukuncodeman** [AlistGo/alist#7093]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [ ] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [ ] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.36.0

### Driver used / 使用的存储驱动

阿里云盘Open

### Describe the bug / 问题描述

failed get objs: failed to list objs: NotFound.ParentFileId:The resource parent_file_id cannot be found. parent_file_id:66cd8675ed9712c2e4c84b77b499a1bedf2fec3d not found

阿里云盘的文件获取接口由https://www.aliyundrive.com/drive/folder/66cd8
变成了https://www.aliyundrive.com/drive/file/all/66cd8

### Reproduction / 复现链接

无

### Config / 配置

无

**Comment by anwen-anyi** [comment]
1. 检查挂载类型是否正确，这个路径文件是否来自阿里云盘 `备份文件` 文件夹中的

      - 如果文件来自阿里云盘非 `备份文件` 这个文件夹之外的 挂载类型选择 `资源库`
      - 如果来自阿里云盘 `备份文件` 文件夹内的，挂载类型 选择备份盘

**Comment by lele1307** [comment]
遇到了相同的问题 xiaoya安装失败
