### ISSUE TITLE
复制任务是否可以排个序？

### ISSUE THREAD

**Issue by flying19880517** [AlistGo/alist#7096]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

我在查看复制任务时，发现运行中和已完成的的任务排序都是乱的，当复制文件比较多时，比如有个10页以上，很难找到特定任务进行取消等。

### Suggested solution / 实现思路

能否先按运行状态排序，先运行中的然后等待中的，再按源路径排序（或目标路径、任务添加顺序等），这样就能迅速定位到想要找的文件了。

**Comment by fgr178707** [comment]
> ### Please make sure of the following things
> * [x]  I have read the [documentation](https://alist.nn.ci).
> * [x]  I'm sure there are no duplicate issues or discussions.
> * [x]  I'm sure this feature is not implemented.
> * [x]  I'm sure it's a reasonable and popular requirement.
> 
> ### Description of the feature / 需求描述
> 我在查看复制任务时，发现运行中和已完成的的任务排序都是乱的，当复制文件比较多时，比如有个10页以上，很难找到特定任务进行取消等。
> 
> ### Suggested solution / 实现思路
> 能否先按运行状态排序，先运行中的然后等待中的，再按源路径排序（或目标路径、任务添加顺序等），这样就能迅速定位到想要找的文件了。
> 
> ### Additional context / 附件
> _No response_

首字母排序  上传进度排序?

**Comment by flying19880517** [comment]
> > ### Please make sure of the following things
> > 
> > * [x]   I have read the [documentation](https://alist.nn.ci).
> > * [x]   I'm sure there are no duplicate issues or discussions.
> > * [x]   I'm sure this feature is not implemented.
> > * [x]   I'm sure it's a reasonable and popular requirement.
> > 
> > ### Description of the feature / 需求描述
> > 我在查看复制任务时，发现运行中和已完成的的任务排序都是乱的，当复制文件比较多时，比如有个10页以上，很难找到特定任务进行取消等。
> > ### Suggested solution / 实现思路
> > 能否先按运行状态排序，先运行中的然后等待中的，再按源路径排序（或目标路径、任务添加顺序等），这样就能迅速定位到想要找的文件了。
> > ### Additional context / 附件
> > _No response_
> 
> 首字母排序 上传进度排序?

可以的，稍微排个序都比现在完全杂乱的强

**Comment by StartMoney** [comment]
加个搜索功能就更好了，同时复制结果也存在这个问题，很杂乱
