### ISSUE TITLE
添加通过FTP/SFTP访问支持

### ISSUE THREAD

**Issue by NpTIme** [AlistGo/alist#7128]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

由于某些众所周知的原因，通在中国大陆境内不易使用 http(s) 协议从公网访问 alist ，且 webdav 协议本身也是通过 http 的。
但是FTP/SFTP协议较为容易通过公网访问，用户可以通过该方法访问并修改alist服务器上的内容。
并且通过freefilesync等软件可以实现跨设备同步文件。
////////////////////////////
其实就是我使用的内网穿透服务给的国内节点不能使用http协议，但是ftp和sftp可以用。

**Comment by Insulinocytus** [comment]
如果你更需要FTP以及SFTP，推荐这个项目
https://github.com/drakkan/sftpgo

**Comment by Simonzhang8** [comment]
FTP/SFTP感觉性能并不好吧，你可以自己再部署个别的服务把FTP/SFTP映射出来

**Comment by KirCute** [comment]
#7634 和 #7643 已实现，这个issue可以close了
