### ISSUE TITLE
别名下文件不能预览

### ISSUE THREAD

**Issue by bingloo** [AlistGo/alist#7242]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.37.4

### Driver used / 使用的存储驱动

webdav

### Describe the bug / 问题描述

原始存储目录下的文件是能预览的，但是设置的别名不能预览，可以下载。（之前是正常的，上一个版本号不记得了）

![image](https://github.com/user-attachments/assets/6b675001-80eb-4fdc-9fb7-9e5c605f72ae)

### Reproduction / 复现链接

暂不提供

### Config / 配置

暂不提供

**Comment by jyhq** [comment]
3.38.0一样的问题

**Comment by xhofe** [comment]
报错信息给全

**Comment by bingloo** [comment]
> 报错信息给全
> 
> 或提供复现链接

方便上下tg吗，我把链接私法给你

**Comment by bingloo** [comment]
> 报错信息给全
> 
> 或提供复现链接

刚刚给你私信发tg了，有空看下私信修复下哈~ 谢谢

**Comment by xhofe** [comment]
开了cf五秒盾 代理程序无法获取文件内容

**Comment by bingloo** [comment]
> 开了cf五秒盾 代理程序无法获取文件内容

刚刚分析了下日志，发现是服务器所在国家没放到白名单，这里的逻辑是程序会请求自己的域名，抱歉，打扰了！

**Comment by zdbit** [comment]
我遇到了相同的问题，如果使用别名，局域网的主机名，alist打开zip的时候，会预览压缩包而不是下载，导致报错：
failed to get /水印管家专业版shuiyinguanjia_pj_v*******0_itmop.com.zip archive met: http request failure, err:Get "http://hiksemi-r1-5615:9020/share/%E6%B0%B4%E5%8D%B0%E7%AE%A1%E5%AE%B6%E7%A0%B4%E8%A7%A3%E7%89%88shuiyinguanjia_pj_v*******0_itmop.com.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=5BLK04aEZkMzmcoYOHPW%2F20250806%2Falist%2Fs3%2Faws4_request&X-Amz-Date=20250806T160343Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E6%25B0%25B4%25E5%258D%25B0%25E7%25AE%25A1%25E5%25AE%25B6%25E7%25A0%25B4%25E8%25A7%25A3%25E7%2589%2588shuiyinguanjia_pj_v*******0_itmop.com.zip&X-Amz-Signature=f1d557173f678371882f1fb9a98ca7f7cf9f04332bafac8bff4f15ac54fe9842": dial tcp: lookup hiksemi-r1-5615 on *********:53: no such host: http request failure, err:Get "http://hiksemi-r1-5615:9020/share/%E6%B0%B4%E5%8D%B0%E7%AE%A1%E5%AE%B6%E7%A0%B4%E8%A7%A3%E7%89%88shuiyinguanjia_pj_v*******0_itmop.com.zip?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=5BLK04aEZkMzmcoYOHPW%2F20250806%2Falist%2Fs3%2Faws4_request&X-Amz-Date=20250806T160343Z&X-Amz-Expires=14400&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B%20filename%2A%3DUTF-8%27%27%25E6%25B0%25B4%25E5%258D%25B0%25E7%25AE%25A1%25E5%25AE%25B6%25E7%25A0%25B4%25E8%25A7%25A3%25E7%2589%2588shuiyinguanjia_pj_v*******0_itmop.com.zip&X-Amz-Signature=f1d557173f678371882f1fb9a98ca7f7cf9f04332bafac8bff4f15ac54fe9842": dial tcp: lookup hiksemi-r1-5615 on *********:53: no such host
