### ISSUE TITLE
蓝奏云优享版小文件上传失败

### ISSUE THREAD

**Issue by houruomu** [AlistGo/alist#7250]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.37.4

### Driver used / 使用的存储驱动

蓝奏云优享版

### Describe the bug / 问题描述

小于1.3KB的小文件以及空文件无法上传。
使用rclone挂载webdav上传会提示`Failed to copy: Method Not Allowed: 405 Method Not Allowed`
而使用web界面上传会提示_“-1: 未读取到文件大小”_

### Reproduction / 复现链接

上传问题，无法提供链接。

### Config / 配置

<img width="305" alt="image" src="https://github.com/user-attachments/assets/78bfc06d-c1de-47ad-9810-fbd3b8c41f03">

### Logs / 日志

<img width="727" alt="image" src="https://github.com/user-attachments/assets/7e68e61e-9bc7-4626-b440-7d319990c239">
<img width="413" alt="image" src="https://github.com/user-attachments/assets/6e926877-deff-4afb-aa7f-e5df6ce9aca8">

**Comment by houruomu** [comment]
问题仍然存在

**Comment by Jason-Fly** [comment]
可以复现，上传小于1KB的文件时，会报错：
<img width="1098" alt="image" src="https://github.com/user-attachments/assets/a77164d5-9908-4fe4-af39-d21bac3d2f5a">

**Comment by Jason-Fly** [comment]
已定位到问题，在通过`/7n/getUpToken`接口获取`token`时，如果传参中的`fileSize`为`0`，则会报错。
<img width="1562" alt="image" src="https://github.com/user-attachments/assets/60d76276-d138-4ae8-ac1f-473e3d25dce2">

**Comment by Jason-Fly** [comment]
调研了蓝奏云优享版的`/7n/getUpToken`接口，发现他们在将字节数转为`KB`数时是向上取整的，所以改成向上取整应该可以解决。
<img width="737" alt="image" src="https://github.com/user-attachments/assets/618142fd-4f3f-4826-8ec4-f925234e4f2b">

<img width="637" alt="image" src="https://github.com/user-attachments/assets/92a5703f-3b40-4c38-a574-3aa0ae85fd7c">

**Comment by houruomu** [comment]
Hi, 我看到您向上取整的方法是直接+1，请问这样会不会在文件大小是1024字节整数倍的情况下出现问题？

**Comment by houruomu** [comment]
是否使用max(1,(x+1023)/1024)更保险？

**Comment by Jason-Fly** [comment]
> Hi, 我看到您向上取整的方法是直接+1，请问这样会不会在文件大小是1024字节整数倍的情况下出现问题？

感谢指出，您的方案会更严谨；
我尝试生成整数倍的文件进行上传，目前不会产生问题，后续可以进行优化。
<img width="971" alt="image" src="https://github.com/user-attachments/assets/a3632f5d-35ff-499f-a2f6-505f73f16e4c">
