### ISSUE TITLE
希望download页，可以将url生成为二维码

### ISSUE THREAD

**Issue by guiys** [AlistGo/alist#7307]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
- [x] I'm sure there are no duplicate issues or discussions.
- [x] I'm sure this feature is not implemented.
- [x] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

场景：今天想往一个老安卓转一张照片，想到可以先传到内网中alist的本地磁盘，然后用老安卓开浏览器访问alist下载这张照片。但是机器太老，打开alist主页一片空白。
遂只能在安卓上手打url进行下载操作。如果有生成为二维码功能的话，在另一台手机上弹出一个二维码，老安卓用相机一扫，就能直接下载了。

**Comment by Simonzhang8** [comment]
支持
暂时的解决方案是自己弄个二维码的插件

**Comment by SheltonZhu** [comment]
这个纯前端应该就能实现
