### ISSUE TITLE
ts视频格式不支持，可以支持吗？

### ISSUE THREAD

**Issue by guochao00** [AlistGo/alist#7309]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

ts视频格式不支持，经常用到ts格式的文件，手动转换也很麻烦，希望可以增加支持，或者有人知道如何解决吗？

**Comment by ZZ0YY** [comment]
如果你需要看视频的话 推荐使用 kodi，挂载 webdav能够播放 ts

**Comment by jian263994241** [comment]
设置里面 视频格式添加  ts ，  然后 选中文件右键， 用 potpalyer 等外部播放器打开
