### ISSUE TITLE
能不能加个查看文件内容的功能，不是下载

### ISSUE THREAD

**Issue by aogg** [AlistGo/alist#7336]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

首页界面上

**Comment by Simonzhang8** [comment]
点开来就是预览啊

**Comment by aogg** [comment]
太大就会变成下载了

70.45K · 2024-10-16 02:45:30
<img width="951" alt="image" src="https://github.com/user-attachments/assets/03ed1355-5414-4105-8fb8-7ee259f7f470">


麻烦太大也要坚持打开，或者下载旁边多个打开，毕竟手机下载再看太麻烦了

可以的话加个tail和head，这样的功能

**Comment by anwen-anyi** [comment]
后台设置文本预览里面把  **.log** 后缀加上呢

**Comment by Simonzhang8** [comment]
![image](https://github.com/user-attachments/assets/314bcbfc-e445-492d-bccf-25aca91acbcc)
这里尾部加上一个log吗，然后保存刷新就好了
应该不是文件太大的问题，你这个70K也没有很大😂，MB GB级的都能预览呢😂

**Comment by aogg** [comment]
加log成功解决
