### ISSUE TITLE
在alist页面直接播放电影，缓存到了哪里？如何清理缓存？

### ISSUE THREAD

**Issue by liang513** [AlistGo/alist#7347]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

你好！我刚刚购买了mac版的应用，然后挂载了迅雷云盘，转存电影到迅雷云盘，在alist网页页面，直接播放该电影，非常流畅，我的问题是如何清理缓存呢？我用的是Mac，硬盘很小，看高清电影恐怕很快就会用完空间，所以想要请教一下如何清理缓存，谢谢指教！

**Comment by xhofe** [comment]
网页播放无缓存
