### ISSUE TITLE
飞机盘文件夹下文件过多卡死

### ISSUE THREAD

**Issue by rls198** [AlistGo/alist#7357]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.38.0

### Driver used / 使用的存储驱动

飞机盘

### Describe the bug / 问题描述

我有一个文件夹有1600张图片会直接卡死，但是飞机盘的官方网页正常.   使用的排列模式是列表，但是其他网盘并不会这样.

### Reproduction / 复现链接

.

### Config / 配置

.

**Comment by Jason-Fly** [comment]
已复现，定位到了原因：
1. 飞机盘目前是按照 60 条每页进行分页查询的；
2. Alist 查询第1页后没有更新 offset ，导致在 for 循环中一直查询第 1 页，陷入死循环；
<img width="1247" alt="Snipaste_2024-10-20_15-43-47" src="https://github.com/user-attachments/assets/cd0029f7-dd0d-40f7-a66a-26193efe77dd">
3. 所以当文件夹内的文件小于 60 时不会有问题，大于 60 才会出现问题；
4. 蓝奏优享版的 driver 是一样的，实测也会遇到一样的问题，不过蓝奏会及时抛出错误阻止重复请求。
<img width="1352" alt="Snipaste_2024-10-20_15-43-36" src="https://github.com/user-attachments/assets/bc7af901-6be4-46ed-927c-43be3c25aaff">
