### ISSUE TITLE
failed get objs: failed to list objs - 115 drive not loading

### ISSUE THREAD

**Issue by patrickmcc** [AlistGo/alist#7367]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.38.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

今天遇到第二次了，更新过token没过多久又掉了

### Reproduction / 复现链接

-

### Config / 配置

-

### Logs / 日志

failed get objs: failed to list objs: <!doctypehtml><html lang="zh-cn"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible"content="IE=edge,chrome=1"><meta name="data-spm"content="a3c0e"><title>405</title><style>a,body,div,h2,html,p{margin:0;padding:0}a{text-decoration:none;color:#3b6ea3}.container{width:1000px;margin:auto;color:#696969}.header{padding:110px 0}.header .message{height:36px;padding-left:120px;background:url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px;line-height:36px}.main{padding:50px 0;background:#f4f5f7}#block_image{position:relative;left:120px}.footer{margin-top:30px;text-align:right}.footer a{padding:8px 30px;border-radius:10px;border:1px solid #4babec}.footer a:hover{opacity:.8}.alert-shadow{display:none;position:absolute;top:0;left:0;width:100%;height:100%;background:#999;opacity:.5}.alert{display:none;position:absolute;top:200px;left:50%;width:600px;margin-left:-300px;padding-bottom:25px;border:1px solid #ddd;box-shadow:0 2px 2px 1px rgba(0,0,0,.1);background:#fff;font-size:14px;color:#696969}.alert h2{margin:0 2px;padding:10px 15px 5px 15px;font-size:14px;font-weight:400;border-bottom:1px solid #ddd}.alert a{display:block;position:absolute;right:10px;top:8px;width:30px;height:20px;text-align:center}.alert p{padding:20px 15px}</style><body data-spm="7663354"><div data-spm="1998410538"><div class="header"><div class="container"><div class="message"><div id="block_message"></div><div><span id="block_url_tips"></span><strong id="url"></strong></div><div><span id="block_time_tips"></span><strong id="time"></strong></div><div><span id="block_traceid_tips"></span><strong id="traceid"></strong></div></div></div></div><div class="main"><div class="container"><img id="block_image"></div></div><div class="footer"><div class="container"><a target="_blank"id="report"href="javascript:;"data-spm-click="gostr=/waf.123.123;locaid=d001;"style="display:none">误报反馈</a></div></div></div><script>function getRenderData(){var e=document.getElementById("renderData");return JSON.parse(e.innerHTML)}function convertTimestampToString(e){e=parseInt(e,10),e=new Date(e);return e.getFullYear()+"-"+("0"+(e.getMonth()+1)).slice(-2)+"-"+("0"+e.getDate()).slice(-2)+" "+("0"+e.getHours()).slice(-2)+":"+("0"+e.getMinutes()).slice(-2)+":"+("0"+e.getSeconds()).slice(-2)}var en_tips={block_message:"Sorry, your request has been blocked as it may cause potential threats to the server's security.",block_url_tips:"Current URL: ",block_time_tips:"Request Time: ",block_traceid_tips:"Your Request ID is: "},cn_tips={block_message:"很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的访问被阻断。",block_url_tips:"当前网址: ",block_time_tips:"请求时间: ",block_traceid_tips:"您的请求ID是: "};window.onload=function(){var e=getRenderData();if(e){var t,n=cn_tips,i=document.getElementById("block_image");for(t in"en"===e.lang?(n=en_tips,i.src="https://g.alicdn.com/sd-base/static/1.0.5/image/405.png",i.id="en_block"):(i.src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png",document.getElementById("report").style.display="inline"),n)document.getElementById(t).innerText=n[t];i=e.traceid,e=i.slice(8,21);document.getElementById("traceid").innerText=i,document.getElementById("url").innerText=location.href.split("?")[0],document.getElementById("time").innerText=convertTimestampToString(e)}}</script><textarea id="renderData" style="display:none">{"traceid":"784e2c9417294207292618082e0baa","lang":"cn"}</textarea>: unexpected error

**Comment by antoniosinclair** [comment]
跟客服反应，他说没有发现网页无法加载的情况。我不确定是不是限流了，还是服务器有改动，哪怕更新token之后也频繁卡掉，似乎是直接限制了账号访问，在网页端也无法加载主目录信息，只能通过搜索和历史记录等功能变相打开文件（且文件在网页端能正常打开，但是主目录和文件信息均无法获取。
在重新登录之后又能持续正常一段时间，而在没有挂载的登录设备（QR与web分别登录）上，文件能正常访问。

**Comment by raxtany** [comment]
一毛一样的情况，自从阿里云限制非会员和第三方之后，115也一直闹个不停。搞得现在要在线看的话，只能用官方客户端看转码后的视频。

**Comment by antoniosinclair** [comment]
似乎又恢复正常了？（疑惑
QR码登录状态不退的情况下，web抓的cookies能够正常使用，没有出现之前无法读取目录的情况（大雾

**Comment by Deepsea-CN** [comment]
> 跟客服反应，他说没有发现网页无法加载的情况。我不确定是不是限流了，还是服务器有改动，哪怕更新token之后也频繁卡掉，似乎是直接限制了账号访问，在网页端也无法加载主目录信息，只能通过搜索和历史记录等功能变相打开文件（且文件在网页端能正常打开，但是主目录和文件信息均无法获取。 在重新登录之后又能持续正常一段时间，而在没有挂载的登录设备（QR与web分别登录）上，文件能正常访问。

报这个就是你请求api速度太快触发风控了，建议限制一下请求速率，不然容易风控、封号

**Comment by raxtany** [comment]
> > 跟客服反应，他说没有发现网页无法加载的情况。我不确定是不是限流了，还是服务器有，激活更新token之后也卡掉，好像是直接限制了账号访问，在网页端也无法访问加载主目录信息，只能通过搜索和历史记录等功能变相打开文件（且文件在网页端能正常打开，但主目录和文件信息均无法获取。在重新登录之后才能持续正常的一段时间，而在在没有挂载的登录设备（QR与web分别登录）上，文件能正常访问。
> 
> 报这个就是你请求api速度太快触发风控了，建议限制一下请求速度，否则容易风控、封号

请问该如何设置呢，大佬

**Comment by raxtany** [comment]
> > 跟限制客服反应，他说没有发现网页无法加载的情况。我不确定是不是限流了，还是服务器有，激活更新令牌之后也卡掉，希望是直接了账号访问，在网页端也无法访问加载主目录信息，只能通过搜索和历史记录等功能变相打开文件（且文件在网页端能正常打开，但主目录和文件信息均无法获取。在重新登录之后才能持续正常的一段时间，而在在没有挂载的登录设备（QR与web分别登录）上，文件能正常访问。
> 
> 报这个就是你请求api速度太快触发风控了，建议限制一下请求速度，否则很容易风控、封号

请问该如何设置呢？我用了CloudDrive2挂载的也是一样的情况，实在是没办法爽用了

**Comment by antoniosinclair** [comment]
> > 跟客服反应，他说没有发现网页无法加载的情况。我不确定是不是限流了，还是服务器有改动，哪怕更新token之后也频繁卡掉，似乎是直接限制了账号访问，在网页端也无法加载主目录信息，只能通过搜索和历史记录等功能变相打开文件（且文件在网页端能正常打开，但是主目录和文件信息均无法获取。 在重新登录之后又能持续正常一段时间，而在没有挂载的登录设备（QR与web分别登录）上，文件能正常访问。
> 
> 报这个就是你请求api速度太快触发风控了，建议限制一下请求速率，不然容易风控、封号

但是我并没有做改动啊，但是最近这几天却出现了这个情况

**Comment by antoniosinclair** [comment]
似乎又恢复正常了。

**Comment by antoniosinclair** [comment]
限制api请求速率和分页大小之后，暂时正常使用了，不清楚具体是哪个影响大。

**Comment by kaixin1995** [comment]
@antoniosinclair 你好，你的请求速率和分页大小调整到多少了呢？ 我这边也近乎无法使用了。

**Comment by antoniosinclair** [comment]
> @antoniosinclair 你好，你的请求速率和分页大小调整到多少了呢？ 我这边也近乎无法使用了。

我分页输入的500，api是2（因为我同一个文件夹下的文件列表数目比较大，请根据自己频繁使用的目录下文件夹数量调整）

**Comment by patrickmcc** [comment]
> @antoniosinclair 你好，你的请求速率和分页大小调整到多少了呢？ 我这边也近乎无法使用了。

分页1000，api=2，好像暂时解决了

**Comment by prajna0** [comment]
![image](https://github.com/user-attachments/assets/3a65e19d-7fe7-4d10-9aeb-bb0e57c272fd)
解决了

**Comment by patrickmcc** [comment]
https://github.com/AlistGo/alist/issues/7468#issue-2635034911
