### ISSUE TITLE
部分视频无法在线播放，只能下载

### ISSUE THREAD

**Issue by thshu** [AlistGo/alist#7372]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.38.0

### Driver used / 使用的存储驱动

本地存储，百度网盘

### Describe the bug / 问题描述

视频只能下载，不能播放，播放请求返回206
百度网盘：非官方接口，ua已改
本地存储：正常配置

### Reproduction / 复现链接

相关文件

通过百度网盘分享的文件：斗破苍穹
链接:https://pan.baidu.com/s/1q-sG8sjU1DXa6NW4ISzHgQ?pwd=bf36 
提取码:bf36
复制这段内容打开「百度网盘APP 即可获取」

### Config / 配置

![Screenshot_2024-10-21-19-54-28-247_mark via](https://github.com/user-attachments/assets/15ede9f8-135c-4944-8b46-ba05cb1079fa)
![Screenshot_2024-10-21-19-54-31-762_mark via](https://github.com/user-attachments/assets/3dab6693-bf19-4a7e-a772-7aafefca6a5b)

**Comment by eiauo** [comment]
https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件

**Comment by thshu** [comment]
> https://alist.nn.ci/zh/faq/why.html#为什么我不能预览视频或音频文件

我看过这个，但是这个好像不是一样的问题，因为同样的文件我有两次播放出来了，虽然只有三秒
