### ISSUE TITLE
移动云盘现在大文件的上传失败率非常高，经常返回403错误

### ISSUE THREAD

**Issue by skyflying1989** [AlistGo/alist#7444]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.38

### Driver used / 使用的存储驱动

移动云盘

### Describe the bug / 问题描述

使用超过5G以上大文件上传，很容易因为403错误而失败，每次尝试都是重头开始上传。。希望能找到问题，或者参照网页版，可以断点续传，不用重头再来。

### Reproduction / 复现链接

使用超过5G以上大文件上传，很容易因为403错误而失败

### Config / 配置

{
  "force": false,
  "site_url": "http://******:60001",
  "cdn": "",
  "jwt_secret": "TZqNY1SOwORmNMSX",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 60001,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }

### Logs / 日志

DEBU[2024-10-31 22:05:54]/home/runner/work/alist/alist/drivers/139/driver.go:536 github.com/alist-org/alist/v3/drivers/139.(*Yun139).Put() &{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Connection:[keep-alive] Content-Length:[81] Content-Range:[bytes 2097152000-2202009600/5176735533] Date:[Thu, 31 Oct 2024 14:05:54 GMT] Server:[Tengine] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Trace-Flowid:[4122477] X-Trace-Sessionid:[ba18e9b8b0ede113ee773450c5810709]] Body:0x5a56040 ContentLength:81 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x5b16c88 TLS:0x5b88060}
DEBU[2024-10-31 22:06:16]/home/runner/work/alist/alist/drivers/139/driver.go:536 github.com/alist-org/alist/v3/drivers/139.(*Yun139).Put() &{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Connection:[keep-alive] Content-Length:[81] Content-Range:[bytes 2202009600-2306867200/5176735533] Date:[Thu, 31 Oct 2024 14:06:16 GMT] Server:[Tengine] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Trace-Flowid:[3689250] X-Trace-Sessionid:[b048e928ceee075c44afe784cef1710c]] Body:0x54be8f0 ContentLength:81 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x5b16148 TLS:0x5d32120}
DEBU[2024-10-31 22:06:46]/home/runner/work/alist/alist/drivers/139/driver.go:536 github.com/alist-org/alist/v3/drivers/139.(*Yun139).Put() &{Status:200 OK StatusCode:200 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Connection:[keep-alive] Content-Length:[81] Content-Range:[bytes 2306867200-2411724800/5176735533] Date:[Thu, 31 Oct 2024 14:06:46 GMT] Server:[Tengine] Strict-Transport-Security:[max-age=31536000; includeSubDomains] X-Trace-Flowid:[3642050] X-Trace-Sessionid:[bb189fb55a1c9571e02206996938074f]] Body:0x54bead0 ContentLength:81 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x543a1e8 TLS:0x5d32180}
DEBU[2024-10-31 22:06:54]/home/runner/work/alist/alist/drivers/139/driver.go:536 github.com/alist-org/alist/v3/drivers/139.(*Yun139).Put() &{Status:403 Forbidden StatusCode:403 Proto:HTTP/1.1 ProtoMajor:1 ProtoMinor:1 Header:map[Connection:[keep-alive] Content-Length:[84] Content-Range:[bytes 2411724800-2411724800/5176735533] Date:[Thu, 31 Oct 2024 14:06:54 GMT] Server:[Tengine] X-Trace-Flowid:[4079100] X-Trace-Sessionid:[dbfaed68c95f2c5af032c334e34255fb]] Body:0x54bee20 ContentLength:84 TransferEncoding:[] Close:false Uncompressed:false Trailer:map[] Request:0x5b16648 TLS:0x5d32360}
DEBU[2024-10-31 22:06:54]/home/runner/work/alist/alist/internal/op/fs.go:568 github.com/alist-org/alist/v3/internal/op.Put() put file [fg-04.bin] done

**Comment by skyflying1989** [comment]
补充下，用的是移动云盘旧的个人盘上传，不确定新的个人盘是否存在同样的问题

**Comment by 3213778453** [comment]
新个人云问题比旧个人云还严重。上传五、六G，直接请求参数不合法，且没有任何进度。

**Comment by ZZ0YY** [comment]
> 补充下，用的是移动云盘旧的个人盘上传，不确定新的个人盘是否存在同样的问题

之前用旧的上传挺好的，甚至一定程度上忽略了会员限制，还不用下载 到本地再上传，直接下载和上传一起进行的，我是钻石会员，64g的设备让我上传了100g的千与千寻
