### ISSUE TITLE
阿里云文件地址的路径变了导致无法解析自定义挂载的文件目录

### ISSUE THREAD

**Issue by ZhinanWu** [AlistGo/alist#7461]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.39.1

### Driver used / 使用的存储驱动

AliyundriveOpen

### Describe the bug / 问题描述

阿里云个人地址路径变了导致无法挂载
https://www.alipan.com/drive/file/all/<file_id>
错误信息为
failed get objs: failed to list objs: NotFound.ParentFileId:The resource parent_file_id cannot be found. parent_file_id:xxx not found

### Reproduction / 复现链接

在存储类型为AliyundriveOpen会百分百复现

### Config / 配置

与配置文件无关

**Comment by anwen-anyi** [comment]
https://alist.nn.ci/zh/guide/drivers/aliyundrive_open.html#%E4%BA%91%E7%9B%98%E7%B1%BB%E5%9E%8B
如果你挂载的内容是 `备份文件`里面的，添加驱动时 挂载类型选择备份盘
如果不是 `备份文件` 请选择挂载类型为资源库
![image](https://github.com/user-attachments/assets/cde948b5-6f4b-4456-b6c0-6d6140073cc7)

**Comment by ZhinanWu** [comment]
问题已解决
