### ISSUE TITLE
Missing : in url in potplayer and vlc 

### ISSUE THREAD

**Issue by jackthenewbie** [AlistGo/alist#7471]
### Please make sure of the following things

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。
- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.39.1 or latest/master

### Driver used / 使用的存储驱动

Any

### Describe the bug / 问题描述

Like the title said, potplayer and vlc missing : after https 
```potplayer://http//192.168.1.129:5244/d/oD_movies/Movies/As%20...```

https://github.com/user-attachments/assets/58d69112-65d7-43ba-92d8-7c3d41c095ec

### Reproduction / 复现链接

Even your demo page here missing : in the url
https://alist.pages.dev/desktop.mp4
https://al.nn.ci/desktop.mp4
```
vlc://https//al.nn.ci/d/desktop.mp4?sign=K5hsDNZOyclgl86GL5mStVPdfJJwwADSYb2fXr1I8QM=:0
potplayer://https//al.nn.ci/d/desktop.mp4?sign=K5hsDNZOyclgl86GL5mStVPdfJJwwADSYb2fXr1I8QM=:0
```

### Config / 配置

Any

**Comment by anwen-anyi** [comment]
https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206

**Comment by jackthenewbie** [comment]
> Solution：[#7360 (comment)](https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206)

I've confirmed it's a duplicate issue #7360. Solution works great, but it'd be quite annoying to add it for everyone who use my site. Regardless, thank you:) @anwen-anyi

**Comment by anwen-anyi** [comment]
> > Solution：[#7360 (comment)](https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206)
> 
> I've confirmed it's a duplicate issue #7360. Solution works great, but it'd be quite annoying to add it for everyone who use my site. Regardless, thank you:) @anwen-anyi

This should be a browser problem. Edge and 360 do not have this problem.  :sweat_smile: 

```txt
potplayer://http//192.168.31.15:5244/d/BD/360_video.mp4 - Google Chrome

potplayer://http://192.168.31.15:5244/d/BD/360_video.mp4 - Microsoft Edge
potplayer://http://192.168.31.15:5244/d/BD/360_video.mp4 - 360

```

**Comment by jackthenewbie** [comment]
> > > Solution：[#7360 (comment)](https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206)
> > 
> > 
> > I've confirmed it's a duplicate issue #7360. Solution works great, but it'd be quite annoying to add it for everyone who use my site. Regardless, thank you:) @anwen-anyi
> 
> This should be a browser problem. Edge and 360 do not have this problem. 😅
> 
> ```
> potplayer://http//192.168.31.15:5244/d/BD/360_video.mp4 - Google Chrome
> 
> potplayer://http://192.168.31.15:5244/d/BD/360_video.mp4 - Microsoft Edge
> potplayer://http://192.168.31.15:5244/d/BD/360_video.mp4 - 360
> ```
Yes, I just confirmed with Waterfox/Firefox earlier, they also don't have this problem. But as google chrome's popularity, it's hard to ask end-users to use another browser¯\_(ツ)_/¯
