### ISSUE TITLE
挂载路径不存在时反而不能删除存储？？？

### ISSUE THREAD

**Issue by Gloryandel** [AlistGo/alist#7487]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [ ] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.39.1

### Driver used / 使用的存储驱动

TeraBox

### Describe the bug / 问题描述

似乎是挂载失败了，想删除存储，提示存储路径不存在
挂载路径不存在反而不能删除存储？？？
存储：TeraBox
![image_39](https://github.com/user-attachments/assets/a0b5b982-9402-4053-84a7-7035dd8573f4)

### Reproduction / 复现链接

none

### Config / 配置

```json
{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "xxxx",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 10,
    "max_backups": 5,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}
```
![image](https://github.com/user-attachments/assets/512c5c95-39f4-48ac-9d20-01d789dc55ea)

### Logs / 日志

[31mERRO[0m[2024-11-09 19:38:18] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:18 | 200 |      606.35µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"
[31mERRO[0m[2024-11-09 19:38:32] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:32 | 200 |     579.379µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"
[31mERRO[0m[2024-11-09 19:38:33] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:33 | 200 |     449.211µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"
[31mERRO[0m[2024-11-09 19:38:33] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:33 | 200 |       456.7µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"
[31mERRO[0m[2024-11-09 19:38:34] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:34 | 200 |     527.419µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"
[31mERRO[0m[2024-11-09 19:38:34] failed get storage driver: no mount path for an storage is: /TeraBox12 
[GIN] 2024/11/09 - 19:38:34 | 200 |      429.52µs |       10.89.3.2 | POST     "/api/admin/storage/delete?id=11"

**Comment by Deepsea-CN** [comment]
有一个临时解决方案，你创建一个相同路径同样的存储，然后再删就能删了，之前的版本我就这么删的，你可以试试

**Comment by Gloryandel** [comment]
> 有一个临时解决方案，你创建一个相同路径同样的存储，然后再删就能删了，之前的版本我就这么删的，你可以试试

![image](https://github.com/user-attachments/assets/fbda4caf-3717-4bf0-a6df-27dc973e2775)
无法保存

**Comment by Gloryandel** [comment]
> 有一个临时解决方案，你创建一个相同路径同样的存储，然后再删就能删了，之前的版本我就这么删的，你可以试试

通过编辑配置文件删除了

**Comment by Jason-Fly** [comment]
<img width="897" alt="image" src="https://github.com/user-attachments/assets/988c8c0e-3aa1-4e5a-9a88-f4c831a69b6d">

- 我今天也遇到你这个`TeraBox`报错了，是在获取`token`失败时，触发了一个数组越界的`bug`，我当时是通过更换节点区域来临时解决的，`TeraBox`的存储状态就正常了；

- 然后我当时想过要删除这个存储，也删除失败了。

**Comment by Daziax** [comment]
> > 有一个临时解决方案，你创建一个相同路径同样的存储，然后再删就能删了，之前的版本我就这么删的，你可以试试
> 
> 通过编辑配置文件删除了，只是有点疑惑，创建的逻辑居然也混入路径不存在。。。

请教下是哪个配置文件
