### ISSUE TITLE
Terabox Uploading files bigger than 8Gbs with Alist problem. 

### ISSUE THREAD

**Issue by Clouddark75** [AlistGo/alist#7490]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.39.1

### Driver used / 使用的存储驱动

Terabox

### Describe the bug / 问题描述

When uploading anything that is bigger than 8Gbs it will finish, but the file don't appear in the account. Uploading by the site or the App works just fine, I can upload files about 25Gbs without problems. The logs show nothing.

Another thing, sometime, copying a folder to another mount drive, the files gets duplicate after been copy to the new directory (it doesn't happen only with TeraBox). 

### Reproduction / 复现链接

Just upload a file bigger than 8Gbs, 9GBsor 10Gbs will do. 

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "...",
  "token_expires_in": 48,
  "database": {
    "type": "mysql",
    "host": "...",
    "port": 3306,
    "user": "...",
    "password": "...",
    "name": "...",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "0.0.0.0",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "",
    "key_file": "",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": true,
    "name": "data/log/log.log",
    "max_size": 50,
    "max_backups": 30,
    "max_age": 28,
    "compress": false
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": true,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": true
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": true
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  }
}

**Comment by Jason-Fly** [comment]
Hi, I reproduced this issue just now.
There was no problem with the file upload. I uploaded a file named "Samsung-Download-LockScreen.zip", `9.84GB`. It was split into multiple `4MB` chunks, numbered from `0` to `2346`. All these chunks were successfully uploaded.
However, when calling the terabox API at `/api/create`, terabox returned an error code 10 with the message: "create super file failed." This error was not handled by alist, so the webpage incorrectly indicated that the upload was successful, even though there was an issue.
![Snipaste_2024-11-12_19-58-07](https://github.com/user-attachments/assets/86efedea-af67-4ca5-9224-79bbd42351c7)
<img width="1324" alt="Snipaste_2024-11-12_19-56-34" src="https://github.com/user-attachments/assets/6f0f7da0-d814-4bb3-9551-5ae1cd48376e">
![Snipaste_2024-11-12_19-57-20](https://github.com/user-attachments/assets/ddb5fc5a-c605-45d8-81b4-b815d07220e0)
