### ISSUE TITLE
如何使用路径访问

### ISSUE THREAD

**Issue by aba666666** [AlistGo/alist#7494]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [X] I'm sure this feature is not implemented.
- [X] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

使用路径访问，比如www.*.com/alist/

**Comment by YangRucheng** [comment]
配置 -> 网站设置 -> [基本路径](https://alist.nn.ci/zh/config/site.html#%E5%9F%BA%E6%9C%AC%E8%B7%AF%E5%BE%84)（旧版）或 [site_url](https://alist.nn.ci/zh/config/configuration.html#site-url)
