### ISSUE TITLE
阿里云盘token失效（可能导致Alist启动失败）

### ISSUE THREAD

**Issue by leitaosha** [AlistGo/alist#7513]
### Please make sure of the following things

- [x] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [x] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [x] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [x] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3 AlistDeskTop

![PixPin_2024-11-17_19-57-43](https://github.com/user-attachments/assets/b0666751-2d1b-4b88-9445-688e68c8aa83)

### Driver used / 使用的存储驱动

AliyunDrive Open

### Describe the bug / 问题描述

出问题时Alist无法打开
![PixPin_2024-11-17_19-35-50](https://github.com/user-attachments/assets/ce5976a3-9ad7-4a48-beea-5b8ea50c7ed8)
猜测token失效等可能，随即在data.db中删除AliyunDrive后恢复正常访问

### Reproduction / 复现链接

None

### Config / 配置

None

### Logs / 日志

[GIN] 2024/11/17 - 19:35:44 | 200 |            0s |       127.0.0.1 | GET      "/@login?redirect=%2F"
[GIN] 2024/11/17 - 19:35:44 | 200 |            0s |       127.0.0.1 | GET      "/api/public/settings"
[33mWARN[0m[2024-11-17 19:35:58] not enable search                            
[GIN] 2024/11/17 - 19:36:21 | 200 |            0s |       127.0.0.1 | GET      "/@login?redirect=%2F"
[GIN] 2024/11/17 - 19:36:22 | 200 |            0s |       127.0.0.1 | GET      "/api/public/settings"
[31mERRO[0m[2024-11-17 19:38:00] [ali_open] failed to refresh token: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[31mERRO[0m[2024-11-17 19:40:00] [ali_open] failed to refresh token: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[33mWARN[0m[2024-11-17 19:40:15] not enable search                            
[31mERRO[0m[2024-11-17 19:42:16] [ali_open] failed to refresh token: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[31mERRO[0m[2024-11-17 19:44:17] [ali_open] failed to refresh token: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[31mERRO[0m[2024-11-17 19:46:17] [ali_open] failed to refresh token: Post "https://api.nn.ci/alist/ali_open/token": context deadline exceeded (Client.Timeout exceeded while awaiting headers) 
[33mWARN[0m[2024-11-17 19:46:26] not enable search                            
[GIN] 2024/11/17 - 19:46:37 | 200 |            0s |       127.0.0.1 | GET      "/@login?redirect=%2F"
[GIN] 2024/11/17 - 19:46:38 | 200 |      1.6548ms |       127.0.0.1 | GET      "/api/public/settings"
[GIN] 2024/11/17 - 19:46:38 | 200 |            0s |       127.0.0.1 | GET      "/assets/index.d5b376e7.js"
[GIN] 2024/11/17 - 19:46:38 | 200 |            0s |       127.0.0.1 | GET      "/assets/useTitle.c2099cad.js"
[GIN] 2024/11/17 - 19:46:38 | 200 |            0s |       127.0.0.1 | GET      "/assets/webauthn-json.browser-ponyfill.1c672167.js"
[GIN] 2024/11/17 - 19:46:39 | 200 |       505.4µs |       127.0.0.1 | POST     "/api/auth/login/hash"
[GIN] 2024/11/17 - 19:46:39 | 200 |       563.7µs |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/11/17 - 19:46:39 | 200 |            0s |       127.0.0.1 | GET      "/assets/index.2a6ef518.js"
[GIN] 2024/11/17 - 19:46:39 | 200 |            0s |       127.0.0.1 | GET      "/assets/Layout.0b43b868.js"
[GIN] 2024/11/17 - 19:46:39 | 200 |            0s |       127.0.0.1 | GET      "/assets/FolderTree.43c2ba40.js"
[GIN] 2024/11/17 - 19:46:39 | 200 |            0s |       127.0.0.1 | GET      "/assets/index.d3403400.js"
[GIN] 2024/11/17 - 19:46:39 | 200 |          71µs |       127.0.0.1 | GET      "/api/public/offline_download_tools"
[GIN] 2024/11/17 - 19:46:39 | 200 |      4.4711ms |       127.0.0.1 | POST     "/api/fs/get"
[GIN] 2024/11/17 - 19:46:39 | 200 |            0s |       127.0.0.1 | POST     "/api/fs/list"
[GIN] 2024/11/17 - 19:46:40 | 200 |       241.6µs |       127.0.0.1 | GET      "/assets/icon.f7601dae.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |      2.1965ms |       127.0.0.1 | GET      "/assets/Folder.d08ea051.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |       523.9µs |       127.0.0.1 | GET      "/assets/Folder.b511ba9e.css"
[GIN] 2024/11/17 - 19:46:40 | 200 |       522.4µs |       127.0.0.1 | GET      "/assets/index.7a46360f.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |            0s |       127.0.0.1 | GET      "/assets/Paginator.9186a5cc.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |      7.8838ms |       127.0.0.1 | GET      "/assets/video_box.2cc27cc5.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |            0s |       127.0.0.1 | GET      "/assets/_commonjs-dynamic-modules.30ae7933.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |            0s |       127.0.0.1 | GET      "/assets/index.9cace70c.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |            0s |       127.0.0.1 | GET      "/assets/List.dc18ae6e.js"
[GIN] 2024/11/17 - 19:46:40 | 200 |      1.8251ms |       127.0.0.1 | GET      "/assets/helper.154e83b5.js"
[31mERRO[0m[2024-11-17 19:46:42] fs/list: token [st invalid,code:50051]
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700 
[31mERRO[0m[2024-11-17 19:46:42] failed list /夸克: token [st invalid,code:50051]
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
failed get objs 
[GIN] 2024/11/17 - 19:46:42 | 200 |     51.7471ms |       127.0.0.1 | POST     "/api/fs/list"
[GIN] 2024/11/17 - 19:46:47 | 200 |            0s |       127.0.0.1 | POST     "/api/fs/list"
[31mERRO[0m[2024-11-17 19:46:48] fs/list: token [st invalid,code:50051]
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700 
[31mERRO[0m[2024-11-17 19:46:48] failed list /夸克: token [st invalid,code:50051]
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
failed get objs

**Comment by zoope** [comment]
同样的问题

**Comment by FlyRenxing** [comment]
同样的问题，但似乎重试十几次会跳出循环正常启动，然后删除阿里存储即可

**Comment by zoope** [comment]
> 同样的问题，但似乎重试十几次会跳出循环正常启动，然后删除阿里存储即可

你们是怎么删的

**Comment by FlyRenxing** [comment]
系统日志显示重试了十几次就忽略阿里了，然后自动正常启动，启动了删除就行，或者直接去sqllite删

**Comment by xhofe** [comment]
重试几次后会跳过 失败是因为API服务器IO被打满了 已修复。
