### ISSUE TITLE
编译后页面最上面出现白色区域

### ISSUE THREAD

**Issue by chexiansheng** [AlistGo/alist#7543]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.39.3

### Driver used / 使用的存储驱动

本地

### Describe the bug / 问题描述

![QQ图片20241122085436](https://github.com/user-attachments/assets/a528813c-b45b-40df-ad34-d5be79db8eef)
如图
编译几个版本后，均出现页面头部纯白色，无法完整显示的情况，请问如何处理。

### Reproduction / 复现链接

如何。
目前已经换回3.29版

### Config / 配置

未修改。

**Comment by anwen-anyi** [comment]
原生的情况下是没有的，修改了CSS会出现
- 参考修改CSS：https://anwen-anyi.github.io/index/05-head.html
