### ISSUE TITLE
failed get objs: failed to list objs: oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken os.******

### ISSUE THREAD

**Issue by sr1223sr** [AlistGo/alist#7545]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.40.0

### Driver used / 使用的存储驱动

Pikpak

### Describe the bug / 问题描述

使用群晖套件版v3.40.0
failed get objs: failed to list objs: oauth2: "invalid_grant" "invalid refresh token for it may be has been refreshed by other process, more info redis: nil, RefreshToken os.************"
在downloadstation下载大约半小时（十余个文件后）后显示如上错误，重新加载挂载之后恢复，继续下载后再次遇到相同错误。
不进行下载单纯放置过一两个小时后再打开alist的pikpak文件夹也会报同样错误，必须重新加载挂载。
搜索了一下几个月前有类似情况，但在最新版里又出现了，有可能是新bug？
辛苦开发人员，麻烦帮忙看看。

### Reproduction / 复现链接

无

### Config / 配置

![error](https://github.com/user-attachments/assets/515b4742-d66f-4ff0-aaa7-549017c21a4f)

**Comment by FedHoo** [comment]
failed get objs: failed to list objs: Get "https://api-drive.mypikpak.com/drive/v1/files?filters=%7B%22phase%22%3A%7B%22eq%22%3A%22PHASE_TYPE_COMPLETE%22%7D%2C%22trashed%22%3A%7B%22eq%22%3Afalse%7D%7D&limit=100&page_token=&parent_id=VO9Ei_UGYlrBZJ_xQ1yDye7go1&thumbnail_size=SIZE_LARGE&with_audit=true": EOF

我这边也是类似的问题，openwrt，Alist v3.39.1，pikpak挂载上几小时或者1天就会掉。

**Comment by Three-taile-dragon** [comment]
令牌刷新 方式选 `HTTP`

**Comment by sr1223sr** [comment]
> 刷新令牌方法 选 `HTTP`

非常感谢。目前过去两小时暂时没有报错

**Comment by 006lp** [comment]
> 刷新令牌方法 选 `HTTP`

我这边还是不行，仍然隔一段时间会掉，报错failed get objs: failed to list objs: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: Code(4002) - captcha_token expired。
不过，我是分别挂载的同一个pikpak账号的/a，/b，/c文件夹到alist根目录，就会出现这个问题，而单独挂载另一个pikpak账号的/f文件夹始终没掉过，不知道是不是与这有关。

**Comment by Three-taile-dragon** [comment]
> > 刷新令牌方法 选 `HTTP`
> 
> 我这边还是不行，仍然隔一段时间会掉，报错failed get objs: failed to list objs: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: Code(4002) - captcha_token expired。
> 不过，我是分别挂载的同一个pikpak账号的/a，/b，/c文件夹到alist根目录，就会出现这个问题，而单独挂载另一个pikpak账号的/f文件夹始终没掉过，不知道是不是与这有关。

尽量不要一个账号同时在多个驱动中挂载，容易导致令牌刷新冲突

**Comment by 006lp** [comment]
> > > 刷新令牌方法 选 `HTTP`
> > 
> > 我这边还是不行，仍然隔一段时间会掉，报错failed get objs: failed to list objs: ErrorCode: 4002 ,Error: captcha_invalid ,ErrorDescription: Code(4002) - captcha_token expired。
> > 不过，我是分别挂载的同一个pikpak账号的/a，/b，/c文件夹到alist根目录，就会出现这个问题，而单独挂载另一个pikpak账号的/f文件夹始终没掉过，不知道是不是与这有关。
> 
> 尽量不要一个账号同时在多个驱动中挂载，容易导致令牌刷新冲突

是的，现在只挂载一个驱动问题，截止目前暂时就没有出现过了

**Comment by FedHoo** [comment]
我就是挂了3个，应该是冲突了，现在只挂载一个
