### ISSUE TITLE
能添加挂载移动云盘共享群群组文件的功能吗

### ISSUE THREAD

**Issue by simonhust** [AlistGo/alist#7603]
### Please make sure of the following things

- [ ] I have read the [documentation](https://alist.nn.ci).
- [ ] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

这个功能很实用，希望大佬能添加这个功能

**Comment by xrgzs** [comment]
这个貌似占用的是个人云的存储空间

**Comment by xrgzs** [comment]
https://github.com/AlistGo/alist/pull/7591 已加入，等待合并

**Comment by simonhust** [comment]
> 这个貌似占用的是个人云的存储空间

大佬，挂载功能存在bug，对于文件少的共享群挂载功能正常，对于文件多一些的，会出现在一级文件夹无线循环的问题
可以添加这个共享群挂载，可以复现
http://yun.139.com/m/#/invitation?type=1&msgId=1194593156492527284

**Comment by xrgzs** [comment]
> 可以复现

感谢提供测试链接，成功复现

**Comment by xrgzs** [comment]
使用自己创建的Group没有问题，必须要使用其他人的Group才能复现
