### ISSUE TITLE
115网盘无法登陆

### ISSUE THREAD

**Issue by xun188** [AlistGo/alist#7614]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.40.0

### Driver used / 使用的存储驱动

115

### Describe the bug / 问题描述

failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"\/files?aid=1&asc=1&cid=2971466151814495619&fc_mix=0&format=json&limit=56&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

### Reproduction / 复现链接

failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"\/files?aid=1&asc=1&cid=2971466151814495619&fc_mix=0&format=json&limit=56&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

### Config / 配置

failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"\/files?aid=1&asc=1&cid=2971466151814495619&fc_mix=0&format=json&limit=56&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

**Comment by qin9125** [comment]
ck增加了新字段 kid 只能等更新了

**Comment by gxbrave** [comment]
比原来多了KID之后就不能挂载了

**Comment by alexallen1** [comment]
qrcode 要改设备类型暂时能登

**Comment by qin9125** [comment]
> 可以临时换这个版本
> 
> https://github.com/pongfcnkl/alist/actions/runs/12173243540

docker怎么办😳

**Comment by lpcheng1208** [comment]
> > 可以临时换这个版本
> > https://github.com/pongfcnkl/alist/actions/runs/12173243540
> 
> docker怎么办😳

docker 也可以自行替换启动文件啊

**Comment by xiaodatao2007** [comment]
今天突然出现异常，error log:

failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"\/files?aid=1&asc=1&cid=0&fc_mix=0&format=json&limit=10240&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

**Comment by xiaodatao2007** [comment]
> 今天突然出现异常，error log:
> 
> failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"/files?aid=1&asc=1&cid=0&fc_mix=0&format=json&limit=10240&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login

也可以解决上面问题吗？

**Comment by xiaodatao2007** [comment]
> 可以临时换这个版本 https://github.com/pongfcnkl/alist/actions/runs/12173243540

> "error":"登录超时，请重新登录。","errNo":990001

我菜鸟，可以细详说下，如何替换吗？@pongfcnkl

**Comment by xiaodatao2007** [comment]
> > 可以临时换这个版本 https://github.com/pongfcnkl/alist/actions/runs/12173243540
> 
> @pongfcnkl 可以介绍下变更内容吗，是如何解决cookie里新增kid导致的问题
> 
> [这个commit](https://github.com/pongfcnkl/alist/commit/bf68f99d14f32156efe1211b9d3ee8e1b2da3640#diff-a3abd6690352bdaef5ce8f3c0569bd9ac31c48c97f3e59c67cde82f030315bc7L6)里看起来就是修改了115driver包的仓库为[pongfcnkl/115driver](github.com/pongfcnkl/115driver)
> 
> [pongfcnkl/115driver](github.com/pongfcnkl/115driver)仓库里[对比上游](https://github.com/SheltonZhu/115driver/compare/main...pongfcnkl:115driver:main)只改了一个模块名
> 
> 难道关键代码是前几个commit中的升级github.com/SheltonZhu/115driver v1.0.30

@pongfcnkl 一样问题，没有成功。

**Comment by xun188** [comment]
链接: https://caiyun.139.com/m/i?014MdMT3zq8zH  提取码:d4fr  复制内容打开中国移动云盘手机APP，操作更方便哦
我自己编译了个alist_3.40.0-r1_aarch64_cortex-a53版本，大家自己提取，采用上面的新版本，应该可以用，但是要在cookie里加个KID参数

**Comment by xiaodatao2007** [comment]
> 链接: https://caiyun.139.com/m/i?014MdMT3zq8zH 提取码:d4fr 复制内容打开中国移动云盘手机APP，操作更方便哦 我自己编译了个alist_3.40.0-r1_aarch64_cortex-a53版本，大家自己提取，采用上面的新版本，应该可以用，但是要在cookie里加个KID参数

好的， 谢谢，试下。

**Comment by aflyingtree** [comment]
遇到了同样的问题,之前挂载的非115会员账号没事,昨晚想挂个115会员的新账号就一直提示登陆超时.

**Comment by lgw79674057** [comment]
apptv的alist什么更新，也遇到这个问题了

**Comment by zituizhi** [comment]
> apptv的alist什么更新，也遇到这个问题了

真是见了鬼了，之前某些文件夹访问报错，去更新了下没法挂载了，作者不出面说下吗，不是软件适配问题那是115的什么导致无法解决

**Comment by zhuzi6** [comment]
> > apptv的alist什么更新，也遇到这个问题了
> 
> 真是见了鬼了，之前某些文件夹访问报错，去更新了下没法挂载了，作者不出面说下吗，不是软件适配问题那是115的什么导致无法解决

115的cookie增加了一个新参数，要么等作者更新，要么就像上面自己编译一下就可以用了

**Comment by 999k923** [comment]
> > > 可以临时换这个版本
> > > https://github.com/pongfcnkl/alist/actions/runs/12173243540
> > 
> > 
> > docker怎么办😳
> 
> docker 也可以自行替换启动文件啊

Docker怎么替换文件？

**Comment by BANG88** [comment]
@pongfcnkl 谢谢哈可以了，转需，如果遇到有权限问题可以先设置一下权限（假如你是把对应的文件上传到这个位置
`chmod +x /tmp/alist-linux-musl-amd64`，然后再执行cp 操作就可以了。

**Comment by 999k923** [comment]
> > > > > 可以临时换这个版本
> > > > > https://github.com/pongfcnkl/alist/actions/runs/12173243540
> > > > 
> > > > 
> > > > docker怎么办😳
> > > 
> > > 
> > > docker 也可以自行替换启动文件啊
> > 
> > 
> > Docker怎么替换文件？
> 
> 如果用的官方docker镜像，参考下面的命令 docker cp 自己下载的alist二进制路径 容器id:/opt/alist/alist

解决了，谢谢大佬。

**Comment by xiaodatao2007** [comment]
> > > > > > 可以临时换这个版本
> > > > > > https://github.com/pongfcnkl/alist/actions/runs/12173243540
> > > > > 
> > > > > 
> > > > > docker怎么办😳
> > > > 
> > > > 
> > > > docker 也可以自行替换启动文件啊
> > > 
> > > 
> > > Docker怎么替换文件？
> > 
> > 
> > 如果用的官方docker镜像，参考下面的命令 docker cp 自己下载的alist二进制路径 容器id:/opt/alist/alist
> 
> 解决了，谢谢大佬。

今天又提示登录状态异常

> failed get objs: failed to list objs: {"state":false,"error":"登录超时，请重新登录。","errNo":990001,"request":"/files?aid=1&asc=1&cid=0&fc_mix=0&format=json&limit=10240&natsort=0&o=user_ptime&offset=0&record_open_time=1&show_dir=1&snap=0"}: user not login
