### ISSUE TITLE
麻烦修复115登陆和播放视频功能

### ISSUE THREAD

**Issue by myzhongqiang** [AlistGo/alist#7620]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

V3.40

### Driver used / 使用的存储驱动

115网盘

### Describe the bug / 问题描述

麻烦修复115登陆和播放视频功能

### Reproduction / 复现链接

麻烦修复115登陆和播放视频功能

### Config / 配置

麻烦修复115登陆和播放视频功能

**Comment by xun188** [comment]
https://github.com/pongfcnkl/alist
用这个版本自己编译下吧，我自己编译了可以用，cookie里加入KID就好了

**Comment by myzhongqiang** [comment]
> https://github.com/pongfcnkl/alist 用这个版本自己编译下吧，我自己编译了可以用，cookie里加入KID就可以了

我用dock版，不会编译啊，希望作者快点更新了

**Comment by forever-sweet** [comment]
喜欢作者更新一下支持115新cookies的版本，我这2天已经登录的115不让我登录了。

**Comment by alexallen1** [comment]
支持cookie KID=的go版本 amd64 https://1drv.ms/u/s!ArjorAQd6ZAxbV_b6MF7l4h4r4Q?e=gGkX7u
#进入容器
docker exec -it alist /bin/sh
rm -rf alist
把alist.7z解压进去
chmod +x *
exit
