### ISSUE TITLE
视频预览下potplayer和vlc的超链接错误

### ISSUE THREAD

**Issue by NoSetViolin** [AlistGo/alist#7628]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.40.0 (OpenWrt x86_64)

### Driver used / 使用的存储驱动

本地储存

### Describe the bug / 问题描述

已确定问题和修改方式
视频预览界面下面的potplayer和vlc超链接中 在http和//之间缺少冒号

假如一个视频为text.mp4
目前出现问题的超链接为 potplayer://http//10.0.0.63:5244/d/test.mp4
仅需添加一个冒号  修改后： potplayer://http://10.0.0.63:5244/d/test.mp4 即可

### Reproduction / 复现链接

我已确认并知晓如何修复这个问题，此处暂不提供复现链接
下面是问题截图
![image](https://github.com/user-attachments/assets/3add948b-9a3c-4c11-90b3-a8242dd9e9f0)

### Config / 配置

我已确认这不是配置问题，此处暂不提供配置文件

### Logs / 日志

![image](https://github.com/user-attachments/assets/65791d56-d96e-4fcc-98fd-5dee645ebaeb)

**Comment by psacal** [comment]
https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206
此处为解决办法，此为chrome浏览器bug

**Comment by NoSetViolin** [comment]
> [#7360 (comment)](https://github.com/AlistGo/alist/issues/7360#issuecomment-2439544206) 此处为解决办法，此为chrome浏览器bug

感谢，大意了原来是这个原因
