### ISSUE TITLE
使用vpn，主页打不开，无法进入管理界面，挂在也会有问题

### ISSUE THREAD

**Issue by 1238888888** [AlistGo/alist#7653]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.41.0

### Driver used / 使用的存储驱动

百度网盘，阿里云盘，123云盘，夸克网盘

### Describe the bug / 问题描述

打开vpn，就不能进入管理页面，挂在也总是掉线。关闭vpn就正常

### Reproduction / 复现链接

..

### Config / 配置

[log.log](https://github.com/user-attachments/files/18121987/log.log)

**Comment by KirCute** [comment]
我怎么觉得这纯就是vpn把你访问本地主机（alist）的请求也一块代理走了导致的，确定不是网络问题吗

**Comment by 1238888888** [comment]
> 我怎么觉得这纯就是vpn把你访问本地主机（alist）的请求也一块代理走了导致的，确定不是网络问题吗

我哪里会啊，哈哈，会我还用花钱购买客户端啊
