### ISSUE TITLE
中国移动云盘app内创建的文件夹和上传的文件在alist里不可见

### ISSUE THREAD

**Issue by qwqcwcawa** [AlistGo/alist#7684]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

3.41.0

### Driver used / 使用的存储驱动

中国移动云盘

### Describe the bug / 问题描述

https://github.com/user-attachments/assets/91537d49-9f9b-470d-bd76-396e81d4bb6d
如视频，在移动云盘app里创建的文件夹在alist里不可见，在alist里创建的文件夹在移动云盘里也不可见，上传的文件也是如此，以前的文件和文件夹不受影响

### Reproduction / 复现链接

https://github.com/user-attachments/assets/91537d49-9f9b-470d-bd76-396e81d4bb6d

### Config / 配置

{
  "force": false,
  "site_url": "",
  "cdn": "",
  "jwt_secret": "***",
  "token_expires_in": 48,
  "database": {
    "type": "sqlite3",
    "host": "",
    "port": 0,
    "user": "",
    "password": "",
    "name": "",
    "db_file": "data/data.db",
    "table_prefix": "x_",
    "ssl_mode": "",
    "dsn": ""
  },
  "meilisearch": {
    "host": "http://localhost:7700",
    "api_key": "",
    "index_prefix": ""
  },
  "scheme": {
    "address": "127.0.0.1",
    "http_port": 5244,
    "https_port": -1,
    "force_https": false,
    "cert_file": "***",
    "key_file": "***",
    "unix_file": "",
    "unix_file_perm": ""
  },
  "temp_dir": "data/temp",
  "bleve_dir": "data/bleve",
  "dist_dir": "",
  "log": {
    "enable": false,
    "name": "data/log/log.log",
    "max_size": 500,
    "max_backups": 30,
    "max_age": 280,
    "compress": true
  },
  "delayed_start": 0,
  "max_connections": 0,
  "tls_insecure_skip_verify": false,
  "tasks": {
    "download": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": false
    },
    "transfer": {
      "workers": 5,
      "max_retry": 2,
      "task_persistant": false
    },
    "upload": {
      "workers": 5,
      "max_retry": 0,
      "task_persistant": false
    },
    "copy": {
      "workers": 5,
      "max_retry": 1,
      "task_persistant": false
    }
  },
  "cors": {
    "allow_origins": [
      "*"
    ],
    "allow_methods": [
      "*"
    ],
    "allow_headers": [
      "*"
    ]
  },
  "s3": {
    "enable": false,
    "port": 5246,
    "ssl": false
  },
  "ftp": {
    "enable": false,
    "listen": ":5221",
    "find_pasv_port_attempts": 50,
    "active_transfer_port_non_20": false,
    "idle_timeout": 900,
    "connection_timeout": 30,
    "disable_active_mode": false,
    "default_transfer_binary": false,
    "enable_active_conn_ip_check": true,
    "enable_pasv_conn_ip_check": true
  },
  "sftp": {
    "enable": false,
    "listen": ":5222"
  }
}

**Comment by metwhale** [comment]
这是缓存没刷出来吧，alist手动传个文件看看

**Comment by qwqcwcawa** [comment]
> 这是缓存没刷出来吧，alist手动传个文件看看

手动传的文件也看不见
