### ISSUE TITLE
阿里云盘挂载后无法看见备份文件

### ISSUE THREAD

**Issue by yanglovezhi** [AlistGo/alist#7697]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
- [X] I'm sure there are no duplicate issues or discussions.
- [ ] I'm sure this feature is not implemented.
- [ ] I'm sure it's a reasonable and popular requirement.

### Description of the feature / 需求描述

阿里云盘挂载后无法看见备份文件

### Additional context / 附件

![1734839823348](https://github.com/user-attachments/assets/3cfd50e9-45fb-450c-8a08-218bdd383808)

**Comment by kylehz** [comment]
同问
