### ISSUE TITLE
一刻相册挂载报错

### ISSUE THREAD

**Issue by LLCSL** [AlistGo/alist#7725]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.41.0

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

挂在一刻相册报错
`errno: -6, refer to https://photo.baidu.com/union/doc`
![image](https://github.com/user-attachments/assets/710760d8-9340-4572-bf24-9568273eaee7)

### Reproduction / 复现链接

下载的desktop版本  没有直接的链接

### Config / 配置

curl 'http://127.0.0.1:5244/api/admin/storage/update' \
  -H 'Accept: application/json, text/plain, */*' \
  -H 'Accept-Language: zh-CN,zh;q=0.9' \
  -H 'Authorization: ' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json;charset=UTF-8' \
  -H 'Origin: http://127.0.0.1:5244' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://127.0.0.1:5244/@manage/storages/edit/1' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36' \
  -H 'sec-ch-ua: "Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "Windows"' \
  --data-raw '{"id":1,"mount_path":"/一刻相册","order":0,"driver":"BaiduPhoto","cache_expiration":30,"status":"errno: -6, refer to https://photo.baidu.com/union/doc","addition":"{\"cookie\":\".Y_D_3DTSBsyOnD8oo4qwr1LRzjWyuyOg76vNVzw.wUndig\",\"show_type\":\"root\",\"album_id\":\"\",\"delete_origin\":true,\"upload_thread\":\"3\"}","remark":"","modified":"2024-12-28T00:59:25.6432139+08:00","disabled":false,"enable_sign":true,"order_by":"","order_direction":"","extract_folder":"","web_proxy":false,"webdav_policy":"302_redirect","proxy_range":false,"down_proxy_url":""}'

**Comment by anwen-anyi** [comment]
登录一刻相册官网 F12 抓携带cookie的请求即可（文档暂时还未更新暂）
 - **https://photo.baidu.com/photo/web/home**

**Comment by LLCSL** [comment]
可以了
