### ISSUE TITLE
[BUG] 一刻相册无法创建

### ISSUE THREAD

**Issue by SammySnake-d** [AlistGo/alist#7741]
### Please make sure of the following things

- [X] I have read the [documentation](https://alist.nn.ci).
我已经阅读了[文档](https://alist.nn.ci)。

- [X] I'm sure there are no duplicate issues or discussions.
我确定没有重复的issue或讨论。

- [X] I'm sure it's due to `AList` and not something else(such as [Network](https://alist.nn.ci/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host) ,`Dependencies` or `Operational`).
我确定是`AList`的问题，而不是其他原因（例如[网络](https://alist.nn.ci/zh/faq/howto.html#tls-handshake-timeout-read-connection-reset-by-peer-dns-lookup-failed-connect-connection-refused-client-timeout-exceeded-while-awaiting-headers-no-such-host)，`依赖`或`操作`）。

- [X] I'm sure this issue is not fixed in the latest version.
我确定这个问题在最新版本中没有被修复。

### AList Version / AList 版本

v3.41.0

### Driver used / 使用的存储驱动

一刻相册

### Describe the bug / 问题描述

一刻相册无法创建成功。

### Reproduction / 复现链接

![image](https://github.com/user-attachments/assets/f56681ec-dabf-4782-ab9b-74083df830b7)

### Config / 配置
```
{
    "StartUp": {
        "alistAutoStartUp": true,
        "mainAutoStartUp": true,
        "quietAutoStartUp": true,
        "trayIcon": true
    },
  
    "MainWindow": {
        "Language": "zh_CN"
    },
    "QFluentWidgets": {
        "ThemeColor": "#ff009faa",
        "ThemeMode": "Auto"
    }
}
```
### Logs / 日志

[31mERRO[0m[2024-12-29 19:38:53] failed list /相册（一刻）: errno: -6, refer to https://photo.baidu.com/union/doc
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
failed get objs 
[GIN] 2024/12/29 - 19:38:53 | 200 |     95.5258ms |       127.0.0.1 | POST     "/api/fs/list"
[GIN] 2024/12/29 - 19:38:55 | 200 |            0s |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/12/29 - 19:38:55 | 200 |      2.1136ms |       127.0.0.1 | GET      "/assets/index.edde7229.js"
[GIN] 2024/12/29 - 19:38:55 | 200 |      9.7659ms |       127.0.0.1 | GET      "/assets/Profile.904fd006.js"
[GIN] 2024/12/29 - 19:38:57 | 200 |       1.062ms |       127.0.0.1 | GET      "/assets/Storages.3c1e250d.js"
[GIN] 2024/12/29 - 19:38:57 | 200 |     11.4421ms |       127.0.0.1 | GET      "/assets/DeletePopover.2a3ab187.js"
[GIN] 2024/12/29 - 19:38:57 | 200 |      2.2149ms |       127.0.0.1 | GET      "/api/admin/driver/names"
[GIN] 2024/12/29 - 19:38:57 | 200 |     40.6194ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:39:00 | 200 |      3.9256ms |       127.0.0.1 | GET      "/assets/item_type.be442da4.js"
[GIN] 2024/12/29 - 19:39:00 | 200 |      4.8835ms |       127.0.0.1 | GET      "/assets/AddOrEdit.2f23a14a.js"
[GIN] 2024/12/29 - 19:39:00 | 200 |       530.2µs |       127.0.0.1 | GET      "/assets/ResponsiveGrid.7b907ec2.js"
[GIN] 2024/12/29 - 19:39:00 | 200 |     17.9702ms |       127.0.0.1 | GET      "/api/admin/storage/get?id=6"
[GIN] 2024/12/29 - 19:39:00 | 200 |     14.8291ms |       127.0.0.1 | GET      "/api/admin/driver/info?driver=BaiduPhoto"
[GIN] 2024/12/29 - 19:39:07 | 200 |      1.3745ms |       127.0.0.1 | GET      "/"
[GIN] 2024/12/29 - 19:39:08 | 200 |      1.7637ms |       127.0.0.1 | GET      "/api/public/settings"
[GIN] 2024/12/29 - 19:39:09 | 200 |            0s |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/12/29 - 19:39:09 | 200 |       528.8µs |       127.0.0.1 | POST     "/api/fs/get"
[GIN] 2024/12/29 - 19:39:09 | 200 |          19µs |       127.0.0.1 | GET      "/api/public/offline_download_tools"
[GIN] 2024/12/29 - 19:39:09 | 200 |          82µs |       127.0.0.1 | POST     "/api/fs/list"
[31mERRO[0m[2024-12-29 19:40:03] failed init storage: errno: -6, refer to https://photo.baidu.com/union/doc 
[GIN] 2024/12/29 - 19:40:03 | 200 |    343.3975ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[GIN] 2024/12/29 - 19:40:25 | 200 |       368.1µs |       127.0.0.1 | GET      "/api/admin/driver/names"
[GIN] 2024/12/29 - 19:40:25 | 200 |       4.521ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:40:29 | 200 |      2.1255ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:40:30 | 200 |       509.7µs |       127.0.0.1 | GET      "/api/admin/storage/get?id=5"
[GIN] 2024/12/29 - 19:40:30 | 200 |      8.2617ms |       127.0.0.1 | GET      "/api/admin/driver/info?driver=BaiduNetdisk"
[GIN] 2024/12/29 - 19:40:36 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/driver/names"
[GIN] 2024/12/29 - 19:40:36 | 200 |     16.3329ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:40:38 | 200 |      1.3895ms |       127.0.0.1 | GET      "/api/admin/storage/get?id=6"
[GIN] 2024/12/29 - 19:40:38 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/driver/info?driver=BaiduPhoto"
[31mERRO[0m[2024-12-29 19:40:46] failed init storage: errno: -6, refer to https://photo.baidu.com/union/doc 
[GIN] 2024/12/29 - 19:40:46 | 200 |    334.8359ms |       127.0.0.1 | POST     "/api/admin/storage/update"
[GIN] 2024/12/29 - 19:40:59 | 200 |            0s |       127.0.0.1 | GET      "/"
[GIN] 2024/12/29 - 19:40:59 | 200 |         514µs |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/12/29 - 19:41:00 | 200 |            0s |       127.0.0.1 | GET      "/api/public/settings"
[GIN] 2024/12/29 - 19:41:00 | 200 |      1.0169ms |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/12/29 - 19:41:00 | 200 |      1.0004ms |       127.0.0.1 | POST     "/api/fs/get"
[GIN] 2024/12/29 - 19:41:00 | 200 |            0s |       127.0.0.1 | GET      "/api/public/offline_download_tools"
[GIN] 2024/12/29 - 19:41:00 | 200 |            0s |       127.0.0.1 | POST     "/api/fs/list"
[31mERRO[0m[2024-12-29 19:41:04] fs/list: errno: -6, refer to https://photo.baidu.com/union/doc
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700 
[31mERRO[0m[2024-12-29 19:41:04] failed list /相册（一刻）: errno: -6, refer to https://photo.baidu.com/union/doc
failed to list objs
github.com/alist-org/alist/v3/internal/op.List.func1
	/source/internal/op/fs.go:127
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall.func2
	/source/pkg/singleflight/singleflight.go:193
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).doCall
	/source/pkg/singleflight/singleflight.go:195
github.com/alist-org/alist/v3/pkg/singleflight.(*Group[...]).Do
	/source/pkg/singleflight/singleflight.go:108
github.com/alist-org/alist/v3/internal/op.List
	/source/internal/op/fs.go:124
github.com/alist-org/alist/v3/internal/fs.list
	/source/internal/fs/list.go:25
github.com/alist-org/alist/v3/internal/fs.List
	/source/internal/fs/fs.go:22
github.com/alist-org/alist/v3/server/handles.FsList
	/source/server/handles/fsread.go:86
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.Auth
	/source/server/middlewares/auth.go:73
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/alist-org/alist/v3/server/middlewares.StoragesLoaded
	/source/server/middlewares/check.go:14
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.LoggerWithConfig.func1
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/logger.go:249
github.com/gin-gonic/gin.(*Context).Next
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/context.go:185
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:633
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/go/pkg/mod/github.com/gin-gonic/gin@v1.10.0/gin.go:589
net/http.serverHandler.ServeHTTP
	/usr/local/go/src/net/http/server.go:3210
net/http.(*conn).serve
	/usr/local/go/src/net/http/server.go:2092
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1700
failed get objs 
[GIN] 2024/12/29 - 19:41:04 | 200 |    115.9579ms |       127.0.0.1 | POST     "/api/fs/list"
[GIN] 2024/12/29 - 19:41:22 | 200 |       536.3µs |       127.0.0.1 | POST     "/api/fs/list"
[GIN] 2024/12/29 - 19:41:25 | 200 |      1.0679ms |       127.0.0.1 | GET      "/api/me"
[GIN] 2024/12/29 - 19:41:28 | 200 |       1.106ms |       127.0.0.1 | GET      "/api/admin/driver/names"
[GIN] 2024/12/29 - 19:41:28 | 200 |      9.1856ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:41:34 | 200 |      6.0115ms |       127.0.0.1 | POST     "/api/admin/storage/delete?id=6"
[GIN] 2024/12/29 - 19:41:34 | 200 |      1.0679ms |       127.0.0.1 | GET      "/api/admin/storage/list"
[GIN] 2024/12/29 - 19:41:36 | 200 |     55.2175ms |       127.0.0.1 | GET      "/api/admin/driver/list"
[31mERRO[0m[2024-12-29 19:42:00] failed init storage but storage is already created: failed init storage: errno: -6, refer to https://photo.baidu.com/union/doc 
[GIN] 2024/12/29 - 19:42:00 | 200 |    290.7212ms |       127.0.0.1 | POST     "/api/admin/storage/create"
[GIN] 2024/12/29 - 19:42:00 | 200 |            0s |       127.0.0.1 | GET      "/api/admin/storage/get?id=25"
[GIN] 2024/12/29 - 19:42:00 | 200 |       577.5µs |       127.0.0.1 | GET      "/api/admin/driver/info?driver=BaiduPhoto"
[31mERRO[0m[2024-12-29 19:42:06] failed init storage: errno: -6, refer to https://photo.baidu.com/union/doc 
[GIN] 2024/12/29 - 19:42:06 | 200 |     74.5469ms |       127.0.0.1 | POST     "/api/admin/storage/update"

**Comment by zhuzhu88920** [comment]
@SammySnake-d   我也碰到和你一模一样的问题，请问你是如何解决的？
